import sys
sys.path.insert(1, '../')
from applications.Evaluator import Range as r

def BBSB3():
    bb = r.Range()
    sb  = r.Range()

    bb.addPair(9, 14)
    bb.onePairCombo('6', 0.4)
    bb.onePairCombo('7', 0.55)
    bb.onePairCombo('8', 0.75)

    bb.addSuitedGivenFirstCard('A', 10, 13)
    bb.oneSuitedCombo('A', '2', 0.7)
    bb.oneSuitedCombo('A', '3', 0.7)
    bb.oneSuitedCombo('A', '6', 0.1)
    bb.oneSuitedCombo('A', '7', 0.2)
    bb.oneSuitedCombo('A', '9', 0.2)

    bb.oneSuitedCombo('K', '6', 0.25)
    bb.oneSuitedCombo('K', '7', 0.25)
    bb.oneSuitedCombo('K', '8', 0.6)
    bb.oneSuitedCombo('K', '9', 0.5)

    bb.oneSuitedCombo('Q', 'T', 0.7)
    bb.oneSuitedCombo('J', '9', 0.6)
    bb.oneSuitedCombo('J', 'T', 0.8)
    bb.oneSuitedCombo('T', '8', 0.7)
    bb.oneSuitedCombo('9', '7', 0.75)
    bb.oneSuitedCombo('8', '6', 0.45)
    bb.oneSuitedCombo('7', '5', 0.5)
    bb.oneSuitedCombo('6', '4', 0.75)
    bb.oneSuitedCombo('5', '3', 0.75)
    bb.oneSuitedCombo('5', '4', 1)
    bb.oneSuitedCombo('6', '5', 1)
    bb.oneSuitedCombo('7', '6', 1)
    bb.oneSuitedCombo('8', '7', 1)
    bb.oneSuitedCombo('9', '8', 1)
    bb.oneSuitedCombo('T', '9', 1)

    bb.addOffSuitGivenFirstCard('A', 12, 13)
    bb.oneOffSuitCombo('A', 'J', 0.5)
    bb.oneOffSuitCombo('A', '6', 0.4)
    bb.oneOffSuitCombo('A', '4', 0.3)
    bb.oneOffSuitCombo('A', '2', 0.4)

    bb.oneOffSuitCombo('K', '2', 0.1)
    bb.oneOffSuitCombo('K', '3', 0.1)
    bb.oneOffSuitCombo('K', '4', 0.4)
    bb.oneOffSuitCombo('K', '5', 0.45)
    bb.oneOffSuitCombo('K', '6', 0.3)
    bb.oneOffSuitCombo('K', '7', 0.4)
    bb.oneOffSuitCombo('K', '8', 0.4)
    bb.oneOffSuitCombo('K', 'Q', 0.6)

    bb.oneOffSuitCombo('Q', '5', 0.3)
    bb.oneOffSuitCombo('Q', '6', 0.4)
    bb.oneOffSuitCombo('Q', '7', 0.3)
    bb.oneOffSuitCombo('Q', '8', 0.4)
    bb.oneOffSuitCombo('Q', '9', 0.2)

    bb.oneOffSuitCombo('J', '7', 0.6)
    bb.oneOffSuitCombo('J', '8', 0.4)
    bb.oneOffSuitCombo('J', '9', 0.3)
    bb.oneOffSuitCombo('T', '8', 0.2)
    bb.oneOffSuitCombo('T', '7', 0.4)

    sb.addPair(2,8)
    sb.onePairCombo('9', 0.75)

    sb.oneSuitedCombo('A', '2', 0.9)
    sb.oneSuitedCombo('A', '3', 0.8)
    sb.oneSuitedCombo('A', '4', 0.8)
    sb.oneSuitedCombo('A', '5', 0.6)
    sb.oneSuitedCombo('A', 'T', 0.25)
    sb.oneSuitedCombo('A', 'J', 0.25)
    sb.addSuitedGivenFirstCard('A', 6, 9)

    sb.addSuitedGivenFirstCard('K', 6, 9)
    sb.oneSuitedCombo('K', '3', 0.2)
    sb.oneSuitedCombo('K', '4', 0.5)
    sb.oneSuitedCombo('K', '5', 0.5)
    sb.oneSuitedCombo('K', 'T', 0.2)
    sb.oneSuitedCombo('K', 'J', 0.2)
    sb.oneSuitedCombo('K', 'Q', 0.3)

    sb.oneSuitedCombo('Q', '6', 0.5)
    sb.oneSuitedCombo('Q', '7', 0.3)
    sb.oneSuitedCombo('Q', '8', 1)
    sb.oneSuitedCombo('Q', '9', 1)
    sb.oneSuitedCombo('Q', 'T', 0.55)

    sb.oneSuitedCombo('J', '8', 0.75)
    sb.oneSuitedCombo('J', '9', 0.8)
    sb.oneSuitedCombo('J', 'T', 0.5)

    sb.oneSuitedCombo('T', '9', 0.6)
    sb.oneSuitedCombo('T', '8', 0.6)
    sb.oneSuitedCombo('9', '8', 0.8)
    sb.oneSuitedCombo('9', '7', 0.8)
    sb.oneSuitedCombo('8', '7', 0.75)
    sb.oneSuitedCombo('8', '6', 0.3)
    sb.oneSuitedCombo('7', '6', 0.65)
    sb.oneSuitedCombo('7', '5', 0.5)
    sb.oneSuitedCombo('6', '5', 0.75)
    sb.oneSuitedCombo('6', '4', 0.4)
    sb.oneSuitedCombo('5', '4', 0.75)

    sb.oneOffSuitCombo('A', '9', 0.25)

    sb.oneOffSuitCombo('A', 'T', 0.75)
    sb.oneOffSuitCombo('A', 'J', 0.5)
    sb.oneOffSuitCombo('A', 'Q', 0.3)
    sb.oneOffSuitCombo('K', 'Q', 0.75)
    sb.oneOffSuitCombo('K', 'J', 0.75)
    sb.oneOffSuitCombo('K', 'T', 0.5)
    sb.oneOffSuitCombo('Q', 'J', 0.8)
    sb.oneOffSuitCombo('Q', 'T', 0.5)
    sb.oneOffSuitCombo('J', 'T', 0.4)

    return bb, sb
