import sys
sys.path.insert(1, '../')
from applications.Evaluator import Range as r
def COUTG3():
    co = r.Range()
    utg  = r.Range()

    co.addPair(9,14)
    co.onePairCombo('8', 0.65)
    co.onePairCombo('7', 0.4)
    co.onePairCombo('6', 0.3)
    co.addSuitedGivenFirstCard('A', 9, 13)
    co.oneSuitedCombo('A', '8', 0.8)
    co.oneSuitedCombo('A', '7', 0.5)
    co.oneSuitedCombo('A', '5', 1)
    co.oneSuitedCombo('A', '4', 0.6)
    co.addSuitedGivenFirstCard('K', 10, 12)
    co.oneSuitedCombo('K', '9', 0.4)
    co.addSuitedGivenFirstCard('Q', 10, 11)
    co.oneSuitedCombo('J', 'T', 0.5)
    co.oneSuitedCombo('8', '7', 0.1)
    co.oneSuitedCombo('7', '6', 0.15)
    co.oneSuitedCombo('6', '5', 0.2)
    co.oneSuitedCombo('5', '4', 0.1)


    co.oneOffSuitCombo('A', 'K', 1)
    co.oneOffSuitCombo('A', 'Q', 1)
    co.oneOffSuitCombo('A', 'J', 0.2)
    co.oneOffSuitCombo('K', 'Q', 0.4)
    ##########
    utg.onePairCombo('Q', 0.3)
    utg.onePairCombo('J', 0.6)
    utg.onePairCombo('T', 0.75)
    utg.onePairCombo('9', 0.7)
    utg.onePairCombo('8', 0.5)
    utg.onePairCombo('7', 0.5)
    utg.onePairCombo('6', 0.5)
    utg.onePairCombo('5', 0.4)
    utg.onePairCombo('4', 0.35)
    utg.onePairCombo('3', 0.2)
    utg.onePairCombo('2', 0.2)

    utg.oneSuitedCombo('A', 'Q', 0.85)
    utg.oneSuitedCombo('A', 'J', 0.5)
    utg.oneSuitedCombo('A', 'T', 0.5)
    utg.oneSuitedCombo('A', '5', 0.5)
    utg.oneSuitedCombo('A', '4', 0.33)
    utg.oneSuitedCombo('K', 'Q', 0.4)
    utg.oneSuitedCombo('K', 'J', 0.6)
    utg.oneSuitedCombo('K', 'T', 0.4)

    utg.oneSuitedCombo('Q', 'J', 0.4)
    utg.oneSuitedCombo('J', 'T', 0.5)
    utg.oneSuitedCombo('T', '9', 0.4)
    utg.oneSuitedCombo('8', '7', 0.3)
    utg.oneSuitedCombo('7', '6', 0.3)
    utg.oneSuitedCombo('6', '5', 0.3)
    utg.oneSuitedCombo('5', '4', 0.3)

    return co, utg 
